### PR TITLE
🎓 Student lecture --- Novelty search intro 

### PR DESCRIPTION
**Pull request by jameshughes89**
### What

I started doing novelty serach topic. It's not done yet, I just wanted to get something down. 

### Why

Prof is making me do it 

### Testing

I built local, Looks good. 

### Additional Notes

I know I'm not done yet, it's only part done.

### CODE REVIEW

**Comment by jameshughes89** [comment]
This is terrible. Try again

**Comment by jameshughes89** [comment]
(ignore this PR)

**Comment by jameshughes89** [comment]
remove because this was an example PR for the lecture

**Comment by twentylemon** [comment]
> This is terrible. Try again

World's best prof

**Pull request closed without merging**
